<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="OpenAI" Version="2.10.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0-preview.3.efcore.9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.7" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="FluentMigrator" Version="7.1.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="7.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LivroDeReceitas.Domain\LivroDeReceitas.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Services\OpenAI\ResourceOpenAI.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourceOpenAI.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Services\OpenAI\ResourceOpenAI.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ResourceOpenAI.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
